export const demoApplicants = [
  {
    id: 1,
    code: 'AG-2026-0001',
    name: 'Maria Theresa Santos',
    program: 'GIP',
    purpose: 'Administrative Assistant',
    status: 'Approved',
    date: 'Aug 18, 2026',
  },
  {
    id: 2,
    code: 'AG-2026-0002',
    name: 'John Michael Dela Cruz',
    program: 'JOB',
    purpose: 'Warehouse Staff',
    status: 'Under Review',
    date: 'Aug 17, 2026',
  },
  {
    id: 3,
    code: 'AG-2026-0003',
    name: 'Angela Mae Flores',
    program: 'SPES',
    purpose: 'Student Assistant',
    status: 'Pending',
    date: 'Aug 16, 2026',
  },
  {
    id: 4,
    code: 'AG-2026-0004',
    name: 'Ronaldo Garcia',
    program: 'GIP',
    purpose: 'Records Clerk',
    status: 'Completed',
    date: 'Aug 15, 2026',
  },
]
